version: "3.7"
services:
    web:
      image: tempapi:latest
      expose:
        - "5000:5000"
      depends_on:
        - mongo
    mongo:
       image: mongo:latest
       ports:
         - "8081:8081"
       volumes:
         - "/home/ubuntu/db:/data/db"
       environment:
         ME_CONFIG_MONGODB_ADMINUSERNAME: root
         MR_CONFIG_MONGODB_ADMINPASSWORD: password
       command: mongod --auth
    proxy:
        image: nginx:latest
        ports:
          - "80:80"
          - "443:443"
        volumes:
           - /etc/letsencrypt/:/etc/letsencrypt/
        links:
          - web